### ISSUE TITLE
Direction

### ISSUE THREAD

**Issue by marksteve** [pythonph/jobs-board#1]
High level discussion on the direction for the jobs board. Just pitch in ideas and I'll collate them here in the issue description.
- We should have a way to track where visitors are coming from. @MrValdez 
- Use subdomain jobs.python.ph. @MrValdez 
- Mailing list (just put a filter what types of jobs you want to get email notifications for) @darylyu 
- Easier way to apply for the job with a click of a button - can make this simple for now, like it could just be a simple button that automatically sends an email/notification to the job poster whenever someone applies for the job @codemickeycode 
- Show date posted so people know which job is recent and which ones are really old @codemickeycode 
- Expiring job posts @darylyu 
- Charging for job posts (maybe in a future iteration) @darylyu

**Comment by MrValdez** [comment]
We should have a way to track where visitors are coming from.

Possible approaches:
-  bit.ly per event.
  Pro: Easy to track and implement
  Con: The url python.ph/jobs will be hidden and will not help in the job board's brand recognition.
- referral code
  Pro: We can add greetings for specific referral code
  Con: We need to standardize the codes, which means we have to implement a different feature for generating them.
  Con: Some users might not use the referral code.
- survey pop-up
  Pro: The URL don't need to change.
  Pro: We can also add other questions such as their skill level.
  Con: Not all visitors will care to answer the questions.
  Con: The UX might not be clean as the user will have another page on top of the jobs board. Examples are newspapers website that asks you to subscribe before you can read the article.

**Comment by marksteve** [comment]
@MrValdez Referral code is easy and doesn't need extra code. Just add a `?ref=PYCON2017` and filter from google analytics

**Comment by MrValdez** [comment]
Use subdomain jobs.python.ph.

This feels more natural to me and easier to read and type from printed materials.

Also, we can apply this to other urls like pycon.python.ph, coc.python.ph, etc.

**Comment by MrValdez** [comment]
@marksteve I think the referral code is the way to go, as well. We just need to standardize the format. Or make a wiki/text files on what each referral code means?

**Comment by marksteve** [comment]
@MrValdez Neutral about subdomains. I honestly think not a lot of people care anymore :P But since we're planning to move the board to a stand-alone webapp, it's easier to have it in a subdomain.
@MrValdez Why the need to standardize? It's for internal use anyways.

**Comment by MrValdez** [comment]
@marksteve Fair point on internal use. I'll start using referral code from now on. :+1:

**Comment by codemickeycode** [comment]
Suggestions:
- mailing list (just put a filter what types of jobs you want to get email notifications for) @darylyu 
- easier way to apply for the job with a click of a button - can make this simple for now, like it could just be a simple button that automatically sends an email/notification to the job poster whenever someone applies for the job

reason: people don't normally check back (both job poster and applicant) until they get an email from a job site
- show date posted so people know which job is recent and which ones are really old

**Comment by darylyu** [comment]
Suggestion:
- expiring job posts
- charging for job posts(maybe in a future iteration)

**Comment by darylyu** [comment]
I think we're basically in agreement on the features. Can we summarize then close this issue? Then we can talk about technical things in the next issue?

**Comment by marksteve** [comment]
@MrValdez  @codemickeycode @darylyu https://github.com/pythonph/jobs-board/issues/3
