### ISSUE TITLE
Bug: No scroll bar after clicking on a job posting.

### ISSUE THREAD

**Issue by MrValdez** [pythonph/jobs-board#2]
On job postings with long descriptions, the box goes off the screen. The scroll bar will be behind the transparent screen and the main scroll bar will not scroll the job posting.

Reproduced on Google Chrome and FireFox with 1366x768 resolution.

Reproduction steps:
1. Click the entry _Software Engineer - Python / Ruby / Javascript / Java / PHP / Scala / .NET / C/C++ / iOS / Android, Based in Singapore or Australia_.

**Comment by marksteve** [comment]
@MrValdez This is going to be a rewrite :)
